name = "Plain Tech"
description = "Technical, minimal Hugo theme using semantic HTML5 and modern vanilla CSS. Automatic light/dark with no JS. System fonts only."
min_version = "0.125.0"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
authors = [
  {name = "Yar Kravtsov", homepage = "https://yarlson.dev"}
]
# Tags and features help discovery in theme galleries
keywords = ["blog", "technical", "minimal", "dark-mode", "accessibility"]
features = ["blog", "taxonomy", "responsive", "dark-mode"]
